# Site settings
title: GIN-Auth Documentation
description: > # this means to ignore newlines until "baseurl:"
  Description for the header
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
collections:
  http_api:
    output: false